### ISSUE TITLE
Upgrade to React Router V6.

### ISSUE THREAD

**Issue by umanda** [tinithkorala/Ifonix-Front-end#1]
**Describe the bug**

React Router V5 is soon deprecated. App should be migrated to React Router V6.

**To Reproduce**

Not applicable

**Expected behavior**
 React Router should be upgraded to latest version and code need to be refactored.

**Screenshots**
Not Applicable

**Additional context**

https://github.com/tinithkorala/Ifonix-Front-end/blob/86b49387376e4f9f879be07714965a833691dae3/package.json#L12

**Comment by tinithkorala** [comment]
React router upgraded to the latest version **(V6)** and refactored the code.
