### ISSUE TITLE
Use sass to organized plain css

### ISSUE THREAD

**Issue by umanda** [tinithkorala/Ifonix-Front-end#2]
**Describe the bug**
Using plain css is hard and difficult to manage. Please convert all plane css to SASS

**To Reproduce**

Not Applicable

**Expected behavior**
All CSS should be derived from SASS

**Screenshots**
Not Applicable

**Additional context**

https://github.com/tinithkorala/Ifonix-Front-end/blob/86b49387376e4f9f879be07714965a833691dae3/src/App.css#L28

**Comment by tinithkorala** [comment]
Converted all plane CSS to SASS
